//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckLoader.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transporter
    {
        public int TransporterId { get; set; }

        [Required(ErrorMessage = "Please Enter Type of Truck")]
        [StringLength(50, MinimumLength = 3)]
        public string TypeOfTruck { get; set; }

        [Required(ErrorMessage = "Please Enter Capacity")]
        public int Capacity { get; set; }

        [Required(ErrorMessage = "Please Enter Location")]
        public string City { get; set; }

        [Required(ErrorMessage = "Please Choose Off Loading Requirement")]
        public string OffLoading { get; set; }

        [Required(ErrorMessage = "Please Choose Off Loading Requirement")]
        public string Refrigerated { get; set; }

        [Required(ErrorMessage = "Please enter Contact Number")]
        [Display(Name = "Contact Number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Please Enter Valid Mobile Number.")]
        public string ContactNumber { get; set; }

        [Required(ErrorMessage = "Please Enter Charges")]
        public int Charges { get; set; }

        [Required(ErrorMessage = "Please Enter Additional Charge")]
        public int AdditionalCharge { get; set; }

        [Required(ErrorMessage = "Please Enter Driver Charge")]
        public int DriverCharge { get; set; }
    }
}
